import { Font, StyleSheet } from "@react-pdf/renderer";

Font.register({
  family: "Cardo",
  src: "/Cardo-Bold.ttf",
});

Font.register({
  family: "Montserrat",
  src: "/Montserrat.ttf",
  fallback: "sans-serif",
});
Font.register({
  family: "GreatVibes",
  src: "/GreatVibes.ttf",
  fallback: "sans-serif",
});

export const styles = StyleSheet.create({
  page: {
    padding: 0,
    backgroundColor: "white",
    position: "relative",
  },
  container: {
    padding: 48,
    height: "100%",
    display: "flex",
    flexDirection: "column",
  },
  // Decorative elements
  decorativeCircle1: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 230,
    height: 230,
    backgroundColor: "#3b82f60d",
    borderRadius: 115,
    opacity: 0.3,
  },
  decorativeCircle2: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: 192,
    height: 192,
    backgroundColor: "#2563eb0d",
    borderRadius: 96,
    opacity: 0.3,
  },
  diagonalLine1: {
    position: "absolute",
    top: 0,
    right: "10%",
    width: 2,
    height: "100%",
    backgroundColor: "#1e3a8a",
    transform: "rotate(12deg)",
    opacity: 0.02,
  },
  diagonalLine2: {
    position: "absolute",
    top: 0,
    right: "20%",
    width: 2,
    height: "100%",
    backgroundColor: "#1e3a8a",
    transform: "rotate(12deg)",
    opacity: 0.02,
  },
  diagonalLine3: {
    position: "absolute",
    top: 0,
    right: "30%",
    width: 2,
    height: "100%",
    backgroundColor: "#1e3a8a",
    transform: "rotate(12deg)",
    opacity: 0.02,
  },
  topBorderLine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 5,
    backgroundColor: "#1e3a8a",
  },
  topGradientLine: {
    position: "absolute",
    top: 48,
    left: 0,
    width: 77,
    height: 2,
    backgroundColor: "#60a5fa33",
  },
  bottomGradientLine: {
    position: "absolute",
    bottom: 77,
    right: 0,
    width: 96,
    height: 2,
    backgroundColor: "#60a5fa33",
  },
  cornerBorderTopLeft: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 58,
    height: 58,
    borderLeftWidth: 2,
    borderTopWidth: 2,
    borderColor: "#1e3a8a1a",
  },
  cornerBorderBottomRight: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 58,
    height: 58,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#1e3a8a1a",
  },
  // Header
  header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 32,
  },
  logoSection: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  logo: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: "#e2e8f0",
    backgroundColor: "white",
  },
  logoImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    padding: 4,
  },
  companyInfo: {
    display: "flex",
    flexDirection: "column",
  },
  companyName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#0f172a",
    fontFamily: "Montserrat",
  },
  companyTagline: {
    fontSize: 14,
    color: "#64748b",
    fontFamily: "Montserrat",
  },
  certIdSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
  },
  certIdLabel: {
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 8,
    color: "#64748b",
    fontFamily: "Montserrat",
  },
  certId: {
    fontSize: 14,
    fontWeight: "semibold",
    color: "#1e3a8a",
    fontFamily: "Montserrat",
  },
  // Main content
  mainContent: {
    display: "flex",
    flexDirection: "row",
    flex: 1,
    gap: 64,
    alignItems: "flex-end",
  },
  contentSection: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  certifyText: {
    fontSize: 18,
    color: "#64748b",
    marginBottom: 24,
    fontFamily: "Montserrat",
  },
  recipientName: {
    fontSize: 56,
    fontWeight: "bold",
    color: "#1e3a8a",
    marginBottom: 3,
    fontFamily: "Montserrat",
    lineHeight: 1.2,
  },
  nameUnderline: {
    width: "100%",
    height: 4,
    backgroundColor: "#1e3a8a",
    marginBottom: 24,
  },
  completionText: {
    fontSize: 16,
    color: "#475569",
    marginBottom: 8,
    lineHeight: 1.625,
    fontFamily: "Montserrat",
    fontWeight: "medium",
  },
  courseName: {
    fontSize: 24,
    fontWeight: "semibold",
    color: "#1e3a8a",
    marginBottom: 8,
    fontFamily: "Montserrat",
  },
  awardedDate: {
    fontSize: 16,
    color: "#475569",
    marginBottom: 16,
    fontFamily: "Montserrat",
    fontWeight: "medium",
    lineHeight: 1.625,
  },
  // Signatures
  signaturesSection: {
    display: "flex",
    flexDirection: "row",
    gap: 32,
    marginTop: 24,
  },
  signatureItem: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  signatureImageContainer: {
    height: 128,
    width: "100%",
    display: "flex",
    alignItems: "flex-end",
    marginBottom: 4,
    position: "relative",
  },
  signatureImage: {
    width: "150%",
    height: "100%",
    objectFit: "contain",
    position: "absolute",
    left: 0,
  },
  signatureLine: {
    height: 32,
    width: "100%",
    marginBottom: 8,
  },
  signatureDivider: {
    width: "100%",
    height: 1,
    backgroundColor: "#cbd5e1",
    marginBottom: 4,
  },
  signatureName: {
    fontSize: 14,
    fontWeight: "semibold",
    color: "#0f172a",
    textAlign: "center",
    fontFamily: "Montserrat",
  },
  signatureTitle: {
    fontSize: 12,
    color: "#64748b",
    textAlign: "center",
    fontFamily: "Montserrat",
  },
  signatureInstitute: {
    fontSize: 12,
    color: "#64748b",
    textAlign: "center",
    fontFamily: "Montserrat",
  },
  // QR Code
  qrSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    marginBottom: 80,
  },
  qrContainer: {
    width: 160,
    height: 160,
    backgroundColor: "white",
    borderWidth: 2,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    padding: 8,
  },
  qrImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
  },
  // Footer
  footer: {
    marginTop: 19,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
  },
  footerText: {
    fontSize: 7,
    color: "#64748b",
    textAlign: "center",
    fontFamily: "Montserrat",
  },
});
