import { Font, StyleSheet } from "@react-pdf/renderer";

Font.register({
  family: "Cardo",
  src: "/Cardo-Bold.ttf",
});

Font.register({
  family: "Montserrat",
  src: "/Montserrat.ttf",
  fallback: "sans-serif",
});
Font.register({
  family: "GreatVibes",
  src: "/GreatVibes.ttf",
  fallback: "sans-serif",
});

export const styles = StyleSheet.create({
  page: {
    padding: 0,
    backgroundColor: "white",
    position: "relative",
  },
  container: {
    padding: 38,
    height: "100%",
    display: "flex",
    flexDirection: "column",
  },
  // Decorative elements
  decorativeCircle1: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 230,
    height: 230,
    backgroundColor: "#3b82f60d",
    borderRadius: 115,
    opacity: 0.3,
  },
  decorativeCircle2: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: 192,
    height: 192,
    backgroundColor: "#2563eb0d",
    borderRadius: 96,
    opacity: 0.3,
  },
  diagonalLine1: {
    position: "absolute",
    top: 0,
    right: "10%",
    width: 2,
    height: "100%",
    backgroundColor: "#1e3a8a",
    transform: "rotate(12deg)",
    opacity: 0.02,
  },
  diagonalLine2: {
    position: "absolute",
    top: 0,
    right: "20%",
    width: 2,
    height: "100%",
    backgroundColor: "#1e3a8a",
    transform: "rotate(12deg)",
    opacity: 0.02,
  },
  diagonalLine3: {
    position: "absolute",
    top: 0,
    right: "30%",
    width: 2,
    height: "100%",
    backgroundColor: "#1e3a8a",
    transform: "rotate(12deg)",
    opacity: 0.02,
  },
  topBorderLine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 5,
    backgroundColor: "#1e3a8a",
  },
  topGradientLine: {
    position: "absolute",
    top: 48,
    left: 0,
    width: 77,
    height: 2,
    backgroundColor: "#60a5fa33",
  },
  bottomGradientLine: {
    position: "absolute",
    bottom: 77,
    right: 0,
    width: 96,
    height: 2,
    backgroundColor: "#60a5fa33",
  },
  cornerBorderTopLeft: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 58,
    height: 58,
    borderLeftWidth: 2,
    borderTopWidth: 2,
    borderColor: "#1e3a8a1a",
  },
  cornerBorderBottomRight: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 58,
    height: 58,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#1e3a8a1a",
  },
  // Header
  header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 29,
  },
  logoSection: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  logo: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 2,
    borderColor: "#e2e8f0",
    backgroundColor: "white",
  },
  logoImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    padding: 2,
  },
  companyInfo: {
    display: "flex",
    flexDirection: "column",
  },
  companyName: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#0f172a",
    fontFamily: "Montserrat",
  },
  companyTagline: {
    fontSize: 8,
    color: "#64748b",
    fontFamily: "Montserrat",
  },
  certIdSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
  },
  certIdLabel: {
    fontSize: 7,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 2,
    color: "#64748b",
    fontFamily: "Montserrat",
  },
  certId: {
    fontSize: 8,
    fontWeight: "semibold",
    color: "#0f172a",
    fontFamily: "Montserrat",
  },
  // Main content
  mainContent: {
    display: "flex",
    flexDirection: "row",
    flex: 1,
    gap: 38,
  },
  contentSection: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  certifyText: {
    fontSize: 11,
    color: "#64748b",
    marginBottom: 19,
    fontFamily: "Montserrat",
  },
  recipientName: {
    fontSize: 38,
    fontWeight: "bold",
    color: "#1e40af",
    marginBottom: 10,
    fontFamily: "GreatVibes",
    textTransform: "capitalize",
  },
  nameUnderline: {
    width: "100%",
    height: 2,
    backgroundColor: "#1e40af",
    marginBottom: 19,
  },
  completionText: {
    fontSize: 8,
    color: "#64748b",
    marginBottom: 14,
    lineHeight: 1.5,
    fontFamily: "Montserrat",
  },
  courseName: {
    fontSize: 14,
    fontWeight: "semibold",
    color: "#0f172a",
    marginBottom: 19,
    fontFamily: "Montserrat",
  },
  awardedDate: {
    fontSize: 10,
    color: "#0f172a",
    marginBottom: 10,
    fontFamily: "Montserrat",
  },
  // Signatures
  signaturesSection: {
    display: "flex",
    flexDirection: "row",
    gap: 10,
    marginTop: 19,
  },
  signatureItem: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  signatureLine: {
    height: 5,
    marginBottom: 5,
  },
  signatureName: {
    fontSize: 8,
    fontWeight: "semibold",
    color: "#0f172a",
    fontFamily: "Montserrat",
  },
  signatureTitle: {
    fontSize: 7,
    color: "#64748b",
    fontFamily: "Montserrat",
  },
  // QR Code
  qrSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  qrContainer: {
    width: 115,
    height: 115,
    backgroundColor: "white",
    borderWidth: 2,
    borderColor: "#cbd5e1",
    borderRadius: 5,
    padding: 5,
  },
  qrImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
  },
  // Footer
  footer: {
    marginTop: 19,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
  },
  footerText: {
    fontSize: 7,
    color: "#64748b",
    textAlign: "center",
    fontFamily: "Montserrat",
  },
});
